dist: xenial
language: python
python:
  - 3.7
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pytest preacher
after_success:
  - codecov
notifications:
  - email: false
