language: python
python:
  - 3.7
virtualenv:
  system_site_packages: true
install:
  - pip install poetry
script:
  # Test no-dev running
  - poetry install --no-dev
  - poetry run preacher-cli --help

  - poetry install
  - poetry run pytest
after_success:
  - codecov
notifications:
  - email: false
