version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install poetry

      - run: poetry install --no-dev
      - run: poetry run preacher-cli --help

      - run: poetry install
      - run: poetry run pytest
      - run: portry run codecov
