version: 2.1

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-3.8
      - test-3.7
      - deploy:
          requires:
            - test-3.8
            - test-3.7

jobs:
  test-3.8:  # Primary
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - install-poetry
      - run:
          name: Run with no dev package
          command: |
            poetry install --no-dev
            poetry run preacher-cli --version
            poetry run preacher-cli --help
      - run:
          name: Run unit tests
          command: |
            poetry install
            poetry run pytest
      - run:
          name: Build documents
          command: poetry run make html
      - run:
          name: Send the test coverage report
          command: |
            sudo pip install codecov
            codecov

  test-3.7:  # Secondary
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install-poetry
      - run:
          name: Run with no dev package
          command: |
            poetry install --no-dev
            poetry run preacher-cli --version
            poetry run preacher-cli --help
      - run:
          name: Run unit tests
          command: |
            poetry install
            poetry run pytest
      - run:
          name: Build documents
          command: poetry run make html
      - run:
          name: Send the test coverage report
          command: |
            sudo pip install codecov
            codecov

  deploy:
    requires:
      - test
    filters:
      #branches:
      #  ignore: /.*/
      #tags:
      #  only: /[0-9]+(\.[0-9]+)*/
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install-poetry
      - run:
          name: Build
          command: poetry build
      #- run:
      #    name: Publish
      #    command: Poetry publish

commands:
  install-poetry:
    description: Install Poetry
    steps:
      - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python